FROM python:3.10-slim AS builder
COPY requirements.txt .
RUN apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install --no-install-recommends -y python3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/* \
COPY --from=builder /usr/local/lib/python3.10/site-packages/ /usr/local/lib/python3.10/dist-packages/
COPY main.py .
CMD ["python3", "main.py"]
